import type { Metadata } from "next";
import Header from "@/components/header/Header";
import HeaderNav from "@/components/header/HeaderNav";
import Logo from "@/components/header/Logo";
import "./globals.css";
import "../styles/index.css";
import Login from "@/components/header/Logout";
import MobileBtn from "@/components/header/MobileBtn";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header>
          <Logo/>
          <HeaderNav/>
          <Login/>
          <MobileBtn/>
        </Header>
        {children}
      </body>
    </html>
  );
}
